### ISSUE TITLE
[ts-json-api] Types do not allow arbitrary property access of objects within attributes

### ISSUE THREAD

**Issue by openjck** [rmarganti/json-api#10]
Thank you for this helpful package.

If I'm not mistaken, it seems that properties of objects within `Attributes` cannot be accessed type-safely.

Given this code:

```javascript
import type { ResourceObject, Response } from "ts-json-api";

const response: Response<ResourceObject> = getResponse();
console.log(response?.data?.attributes?.query?.value);
```

The following error is raised by tsc:

```
TS2339: Property 'value' does not exist on type 'string | number | boolean | object'.
   Property 'value' does not exist on type 'string'.
```

Could this be corrected by adding the optional type `Record<string, any>` to `Attributes`?

**Comment by rmarganti** [comment]
While I do agree that the typing here can be improved (type-fest has a better [definition of valid JSON values](https://github.com/sindresorhus/type-fest/blob/main/source/basic.d.ts)), that wouldn't actually solve this exact issue.

Because properties of `attributes` are defined as "one the possible types: string, number, boolean, object", you will always have to do some type checking. For example, if `attributes.query` is a string, the `value` sub-property isn't valid.

The current best way to handle this for now shapes is be specific.



```typescript
import type { ResourceObject, Response } from "ts-json-api";

interface QueryResource extends ResourceObject {
    attributes: {
        query: {
            value: string;
            ...
        }
    }
}

const response: Response<QueryResource> = getResponse();
```

**Comment by openjck** [comment]
Thank you very much. I'm somewhat new to TypeScript and found this to be helpful.
